### ISSUE TITLE
Pokemon Go Ban

### ISSUE THREAD

**Issue by eescobar** [nguyenhuuduy6592/pokemongo-webspoof#1]
Hi!
I usually use the code from the original project, but 4 days ago I receive a 90 days ban from Niantic.
I don't know how they catched me... =(

Do you know if your update for this project has a system to block Niantic to know that this is a GPS Simulator?

Thank you for your help.

**Comment by nguyenhuuduy6592** [comment]
I'm afraid that this project does not have any thing like that.
Anyway, nothing is safe. If you decide to spoof, never use your main account.
