### ISSUE TITLE
how to compile and run the project?

### ISSUE THREAD

**Issue by fmchan** [nguyenhuuduy6592/pokemongo-webspoof#2]
i used the original one which is pokemongo-webspoof.app.tar.gz (v1.2.1)
but then i found your modification is good. however i don't know how to run it, would you mind sharing some hints? thank you!

**Comment by nguyenhuuduy6592** [comment]
In the original repo, the developer has the guide to compile and run it.
Please check on this link: https://github.com/iam4x/pokemongo-webspoof -> Section **Develop**
